[package]
name = "budget-data-server"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "budget-data-server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ynab = { path = "./ynab", features = ["sqlx-postgres"] }

anyhow = "1.0.68"
axum = "0.6.4"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { version = "1.24.2", features = ["full"] }
tower = "0.4.13"
sqlx = { version = "0.6.2", default-features = false, features = ["runtime-tokio-rustls", "postgres", "macros", "uuid", "chrono", "migrate", "json"] }
figment = { version = "0.10.7", features = ["env", "toml"] }
secrecy = { version = "0.8.0", features = ["serde"] }
redis = { version = "0.22.2", features = ["tokio-comp"] }

[workspace]
members = [
    "budget-data-api",
    "ynab",
]

[workspace.dependencies]
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
chrono = "0.4.23"
rrule = "0.10.0"
uuid = { version = "1.2.2", features = ["serde"] }
