[package]
name = "datamize"
version = "0.1.0"
authors = ["Jeremy Dube <jeremy.dube.dev@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "datamize"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ynab = { path = "./ynab", features = ["sqlx-postgres"] }
anyhow = { workspace = true }
axum = "0.6"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true }
tower = { version = "0.4.13" }
sqlx = { version = "^0.7.0", features = ["runtime-tokio", "tls-rustls", "postgres", "macros", "uuid", "chrono", "migrate", "json"] }
secrecy = { version = "0.8.0", features = ["serde"] }
redis = { version = "0.23", features = ["tokio-comp", "r2d2"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "registry"] }
tower-http = { version = "^0.4.1", features = ["trace", "cors"] }
tracing-log = "0.1.3"
config = { version = "0.13.3", features = ["toml"], default-features = false }
r2d2 = "0.8.10"
uuid = { workspace = true }
chrono = { workspace = true }
futures = "^0.3.28"
serde_repr = "^0.1.14"
axum-extra = "^0.7.4"
num-traits = "0.2.15"
async-recursion = "^1.0.4"
fantoccini = { version = "0.19.3", features = ["rustls-tls"] }
nom = "7.1.3"
orion = { workspace = true }
http = "0.2.9"
tower-request-id = "0.2.1"
rrule = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
fake = { version = "^2.6.1", features = ["chrono", "derive", "uuid"] }
once_cell = "1.18"
rand = "^0.8.5"
reqwest = { workspace = true }
wiremock = "^0.5.19"

[workspace]
members = [
    "datamize-cli",
    "ynab",
]

[workspace.dependencies]
tokio = { version = "1.29", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "^0.4.26"
rrule = "^0.10.0"
anyhow = { version = "1.0", features = ["backtrace"] }
thiserror = "1.0"
reqwest = { version = "^0.11.18", default-features = false, features = ["json", "cookies", "rustls-tls"] }
uuid = { version = "1.4", features = ["serde", "v4"] }
orion = "^0.17.5"
