[package]
name = "datamize"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "datamize"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ynab = { path = "./ynab", features = ["sqlx-postgres"] }
budget-data-api = { path = "./budget-data-api" }
anyhow = { version = "1.0.68", features = ["backtrace"] }
axum = "0.6.4"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { version = "1.24.2", features = ["full"] }
tower = { version = "0.4.13" }
sqlx = { version = "0.6.2", default-features = false, features = ["runtime-tokio-rustls", "postgres", "macros", "uuid", "chrono", "migrate", "json", "offline"] }
secrecy = { version = "0.8.0", features = ["serde"] }
redis = { version = "0.22.2", features = ["tokio-comp", "r2d2"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "registry"] }
tower-http = { version = "0.3.5", features = ["trace", "cors"] }
tracing-log = "0.1.3"
config = { version = "0.13.3", features = ["toml"], default-features = false }
r2d2 = "0.8.10"
uuid = { workspace = true }
futures = "0.3.25"

[workspace]
members = [
    "budget-data-api",
    "ynab",
]

[workspace.dependencies]
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
chrono = "0.4.23"
rrule = "0.10.0"
uuid = { version = "1.2.2", features = ["serde"] }
