version: "3.9"
name: datamize
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATAMIZE_ENVIRONMENT: "staging"
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: datamize
  redis:
    image: "redis"
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  db:
  redis:
    driver: local
