-- Create Categories Table
CREATE TABLE categories(
  id BLOB NOT NULL,
  category_group_id BLOB NOT NULL,
  category_group_name TEXT NOT NULL,
  name TEXT NOT NULL,
  hidden BOOLEAN NOT NULL,
  original_category_group_id BLOB,
  note TEXT,
  budgeted BIGINT NOT NULL,
  activity BIGINT NOT NULL,
  balance BIGINT NOT NULL,
  goal_type TEXT,
  goal_day INTEGER,
  goal_cadence INTEGER,
  goal_cadence_frequency INTEGER,
  goal_creation_month DATE,
  goal_target BIGINT,
  goal_target_month DATE,
  goal_percentage_complete INTEGER,
  goal_months_to_budget INTEGER,
  goal_under_funded BIGINT,
  goal_overall_funded BIGINT,
  goal_overall_left BIGINT,
  deleted BOOLEAN NOT NULL,
  PRIMARY KEY (id)
);
