[application]
host = "0.0.0.0"
port = 8000
base_url = ""

[ynab_client]
pat = ""
pat_file = ""
base_url = "https://api.youneedabudget.com/v1/"
client_id = ""
client_secret = ""
redirect_url = "http://localhost:4300"
# redirect_url = "http://127.0.0.1:7000/oauth/callback"
auth_url = "https://app.ynab.com/oauth/authorize"
token_url = "https://app.ynab.com/oauth/token"

[database]
username = "postgres"
password = "password"
port = 5432
host = "127.0.0.1"
database_name = "datamize"
require_ssl = false

[redis]
host = "127.0.0.1"
port = 6379

[webdriver]
host = "127.0.0.1"
port = 4444
