[application]
host = "0.0.0.0"
port = 8000
base_url = ""

[ynab_client]
pat = ""
pat_file = ""
base_url = "https://api.youneedabudget.com/v1/"

[database]
username = "postgres"
password = "password"
port = 5432
host = "127.0.0.1"
database_name = "datamize"
require_ssl = false

[redis]
host = "127.0.0.1"
port = 6379

[webdriver]
host = "127.0.0.1"
port = 4444
